"""Add telegram_id to Candidate

Revision ID: 762a187b70ae
Revises: 
Create Date: 2025-07-24 14:47:02.231303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762a187b70ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('telegram_id', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('results', sa.String(), nullable=True))
    op.drop_column('candidates', 'phone')
    op.drop_column('candidates', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'results')
    op.drop_column('candidates', 'telegram_id')
    # ### end Alembic commands ###
